### ISSUE TITLE
How do I change what color the unclosed paren is highlighted in?

### ISSUE THREAD

**Issue by umnikos** [arnar/vim-matchopen#1]
In my vim matching parens and unclosed parens are highlighted in the same color and it gets really hard to keep track of which is which.

**Comment by arnar** [comment]
See updated README.md

In short, update the plugin add this to your .vimrc:

    hi MatchOpen <whatever you want>

or link it with an existing group (execute `:hi` to see a list of active groups):

    hi link MatchOpen <group you'd like to use>
